### ISSUE TITLE
关于召回文档数量的评估

### ISSUE THREAD

**Issue by wyzhhhh** [RUCAIBox/LLM-Knowledge-Boundary#3]
我想请问一下，在文章中关于召回越多文档回答越准确这个实验的prompt是如何设置的？是将检索到的文档都作为prompt传入LLM让其回答吗？

**Comment by yhao-wang** [comment]
论文第二章有详细介绍，代码中也可以看到

**Comment by wyzhhhh** [comment]
请问是直接把检索到的文档作为prompt+query传入LLM进行回答吗？论文第二章提到的意思是指：传入的检索文档越多，回答的效果越好吗？麻烦赐教

**Comment by yhao-wang** [comment]
我们的实验是将检索到的文档作为prompt+query传入LLM
