### ISSUE TITLE
请问如何评测结果？

### ISSUE THREAD

**Issue by dongguanting** [RUCAIBox/LLM-Knowledge-Boundary#4]
<img width="841" alt="image" src="https://github.com/RUCAIBox/LLM-Knowledge-Boundary/assets/60767110/64476934-44a9-40a9-8f9f-314a03c1a29d">
您好，我按照脚本已经生成了nq-chat.json，请问如何评测我生成结果的EM或者F1分数？
请问是否可以提供评测脚本吗？或者有没有示例评测代码？

**Comment by dongguanting** [comment]
哈喽？@yhao-wang

**Comment by yhao-wang** [comment]
这个是生成参考文档，并非生成答案，运行后续脚本会自动评测各项指标的

**Comment by dongguanting** [comment]
> 这个是生成参考文档，并非生成答案，运行后续脚本会自动评测各项指标的
@yhao-wang 
以spare检索器，QA设置下的NQ test集为例，我看运行后输出的json文件，3610个sample每个sample都会有一个EM与F1，那请问最终结果，是计算3600个样本的中EM平均分数与F1平均分数吗？

**Comment by yhao-wang** [comment]
对的~
